version: "3"

services:
  devzone:
    image: "ubuntu:lunar"
    stdin_open: true
    tty: true
    volumes:
      - ../:/app:rw
    network_mode: host
    environment:
      - DISPLAY
    entrypoint: /bin/bash
